plugin:
  name: PythonParts SDK
  UUID: b8b5051d-bade-4ea6-961b-f6d9129ba6cf
  version: 2.0.1
  developer: allplan_gmbh
  default-language: en
  min-allplan-version: 2026

installation:
  target-location: USR

tools:
  - id: start-python-debug
    pyp: Library\Allplan GmbH\PythonParts SDK\StartPythonDebug.pyp
    display-name:
      en: Start Python Debug
      de: Python Debug starten
    icons:
      small: PythonPartsActionbar\allplan_gmbh\pythonparts_sdk\StartPythonDebug_24.png
      large: PythonPartsActionbar\allplan_gmbh\pythonparts_sdk\StartPythonDebug_128.png
  - id: install-python-package
    pyp: Library\Allplan GmbH\PythonParts SDK\InstallPythonPackage.pyp
    display-name:
      en: Install Python Package
      de: Python Package installieren
    icons:
      small: PythonPartsActionbar\allplan_gmbh\pythonparts_sdk\InstallPythonPackage_24.png
      large: PythonPartsActionbar\allplan_gmbh\pythonparts_sdk\InstallPythonPackage_128.png
  - id: encrypt-pythonpart-script 
    pyp: Library\Allplan GmbH\PythonParts SDK\EncryptPythonPartScript.pyp
    display-name:
      en: Encrypt PythonPart Script
      de: PythonPart Skript verschlüsseln
    icons:
      small: PythonPartsActionbar\allplan_gmbh\pythonparts_sdk\EncryptPythonPartScript_24.png
      large: PythonPartsActionbar\allplan_gmbh\pythonparts_sdk\EncryptPythonPartScript_128.png
  - id: create-vscode-workspace
    pyp: Library\Allplan GmbH\PythonParts SDK\CreateVisualStudioCodeWorkspace.pyp
    display-name:
      en: Create VS Code Workspace
      de: VS Code Workspace erzeugen
    icons:
      small: PythonPartsActionbar\allplan_gmbh\pythonparts_sdk\CreateVisualStudioCodeWorkspace_24.png
      large: PythonPartsActionbar\allplan_gmbh\pythonparts_sdk\CreateVisualStudioCodeWorkspace_128.png
  - id: download-pythonpart-examples
    pyp: Library\Allplan GmbH\PythonParts SDK\DownloadPythonPartExamples.pyp
    display-name:
      en: Download PythonPart Examples
      de: PythonPart Beispiele herunterladen
    icons:
      small: PythonPartsActionbar\allplan_gmbh\pythonparts_sdk\DownloadPythonPartExamples_24.png
      large: PythonPartsActionbar\allplan_gmbh\pythonparts_sdk\DownloadPythonPartExamples_128.png

task-area:
  display-name:
    en: PythonPart SDK
    de: PythonPart SDK
  layout:
    - start-python-debug
    - "****"
    - create-vscode-workspace
    - ----
    - install-python-package
    - download-pythonpart-examples
    - ----
    - encrypt-pythonpart-script
