name: Release Allep

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Configure Git to preserve CRLF
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create allep file
        uses: vimtor/action-zip@v1.1
        with:
          files: Library/ PythonPartsScripts/ PythonPartsActionbar/ install-config.yml requirements.in
          recursive: false
          dest: PythonPartsSDK.allep

      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            PythonPartsSDK.allep
